#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS.
FILE="/etc/passwd"
while IFS=: read -r username password uid gid info home shell; do
    # Handle empty info field
    if [ -z "$info" ]; then
        info_text=""
    else
        info_text="$info"
    fi

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. UID's place is protected by the passcode $password, more info about the user here: $info_text"
done < "$FILE"
