#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59
i=0
n=1
while [ "$i" -le 12 ]; do
	echo "Hour: $i"
	while [ "$n" -le 59 ];do
	echo "$n"
	n=$((n+1))
	done
i=$((i+1))
done
