#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
echo $$ | sudo tee /var/run/myscript.pid > /dev/null

# Set traps
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm -f /var/run/myscript.pid' SIGQUIT

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
